language: node_js
node_js:
  - node
env:
  global:
    - secure: e74u/QGsRd7E8Ztn+oh8tiN0ylcNWOqGlzbcwB3/uVS7WJd4kP3XklM736NfltSFr6uRpYq/mSBKm8DKlpsCRiACmQ1kZlsz7W0bYAv+0G3qpLmvkKfLjm1nLCjQkpGFPO5AneuJs5Y0tjoMPmQJm/cY2ejauwhy6n6ghg1agME=
    - secure: L/MeKS5XkHrZQeNBii7kLBFIQYerD9At+oaJsGOEMxj31G/xPKE+e/cV0238Bbbf/rH/8V7AMNI8l1O1Nix8H/NzeliVjN3eKUtQfYDew6tiPCaR7f8FWiawpKNTwI49G1i2m50A8K4PTx6jCLs4Wb78PGfWX8SqLpEtQGBm2y0=
